### PR TITLE
Changelog + preFetchOptions

### PR DESCRIPTION
**Pull request by axules**
Hi, @zslucky.
Im create property-method `$payload`.preFetchOptions.
In order to be able to change the titles (or options) just before sending request.

### CODE REVIEW

**Comment by zslucky** [comment]
Hi @axules , do you think it's necessary? looks like we can define different options to avoid this. How do you think?

**Comment by axules** [comment]
@zslucky,
When you need to transfer a file, you should use multipart/form-data and add `boundary`. If Content-Type is undefined, then browser auto append content type and boundary. Can you tell me how to get out of `boundary` FormData object?
If i remove in `preFetchOptions` 'Content-Type' from headers, then its all ok, and file (form) send.

```
function uploadImage (image) { 
   var formData = new FormData(); 
   formData.append('photo', image); 
   fetch('http://localhost:8080/uploadUserImage/', { 
      method:'POST', 
      headers: {
          //in RFM this property default application/json => we need to change the type manually
          'Content-Type': 'multipart/form-data; boundary=**??????**'
      }
      body: formData 
   }); 
}
```
image

**Comment by zslucky** [comment]
Thanks @axules , I will try it, looks like only need to set `Content-Type` to `multipart/form-data`, `boundary ` will be auto added, I will try it in a simple demo and reply you soon. 😄

**Comment by zslucky** [comment]
Hi @axules , I tested and found `boundary` looks like can be auto generated by browser, only set `Content-Type` to `multipart/form-data` is OK, I'm not sure is it blocked you if no `boundary`?

**Comment by axules** [comment]
### Im set `Content-Type` = `multipart/form-data`, result
image
image
-----------------------------------------------
### Im remove `Content-Type`, result:
image
image

**Comment by axules** [comment]
Hi @zslucky.
The server does not understand the request as a form, if not specified boundary in the Content-Type.

**Comment by zslucky** [comment]
@axules  yes you are right, I got it, let me take a look, is there we can use a better method to fix it.

**Comment by zslucky** [comment]
@axules have published, maybe I think we can improve this design in the future.

**Comment by axules** [comment]
@zslucky, yes, I agree.

**Pull request merged**
