### PR TITLE
Add uid request and optimize import lodash.merge

### PR DESCRIPTION
**Pull request by axules**
Hi. Next update completed =)
1. remove lodash and install lodash.merge => less result app.js
2. add customize function generate uid => unique id for request. If in 1 second 3 request => uid last request and save last result by uid.

let lastUid = '';
....
switch (action.type) {
    case 'FETCH_CATEGORY_LIST_REQUEST':
      lastUid = action.$uid;
      return ....
    case 'FETCH_CATEGORY_LIST_SUCCESS':
      if( action.$uid != lastUid ) return state;
      return { ...state, result: action.data,  isFetching: true };

3. CRLF => LF - lint show errors (m.b. is Windows problem)

### CODE REVIEW

**Comment by axules** [comment]
sorry, I forgot to change the version =(

**Comment by zslucky** [comment]
Hi @axules , I think add unique id for per request is a good idea, but I have 2 suggestions:
1. How do you think about to use `node-uuid` to generate v4 uuid instead of your custom function?
2. I prefer to follow [FSA](https://github.com/acdlite/flux-standard-action), so actually I want to move `$prop` and `$uid` into `meta` field, how do you think about this?

I will waiting for your reply, thanks for your great help!

**Comment by zslucky** [comment]
@axules , BTW the demo code in your comment, I think it will affect other requests in the same reducer, maybe you can use a `key-value` type instead of only 1 string value for every individual request. e.g. use `let lastUid = {}` instead of `let lastUid = ''`, how do you think about this?

**Comment by axules** [comment]
1. No problems. I would like to minimize dependence. I do not mind using v4.
2. Replact action.$props to **action.meta.$props**? Replact action.$uid to **action.meta.$uid**?
I'm not against. We in the project are not many places where we use $props.

**Comment by axules** [comment]
In my example of a situation where a lot of requests from the same code REDUX, but with different parameters. We need only the last, then all intermediate to ignore. For example, the search string - when you press a button keyboard, the fly requests, but we only need the last.

**Comment by zslucky** [comment]
@axules, actually only need `meta`, like `$prop.a` => `meta.a`, `$uid` => `meta.uid`, this is the next major release I prefer in future as I'd like to follow FSA.

I will merge it and publish it later, thanks.

**Comment by axules** [comment]
In actions?
{
    type: YOUR_ACTION_TYPE_NAME,
    **//meta or $props?
    $props: {**
        a: 10,
        b: 20
    },
    // @Param: $payload is the detail ajax request description
    $payload: {
......

To REDUX?
action.type = YOUR_ACTION_TYPE_NAME
action.data = ... (result)
**action.meta = {...$props, uid: v4} ?
right?**

**Comment by zslucky** [comment]
@axules never mind, this just a plan for next major release `3.0.0`, it will not impact your project any more. if you just keep using 2+ version. I will create a issue to describe more detail for this change.

I have merged your code, and new version is `2.1.0`, as new feature added, the version number we are followed SemVer2.0.

**Comment by zslucky** [comment]
https://github.com/zslucky/redux-fetch-middleware/issues/5

**Pull request merged**
